apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "axetrading-cronjob.fullname" . }}
  labels:
    {{- include "axetrading-cronjob.labels" . | nindent 4 }}
  namespace: '{{ .Release.Namespace }}'
spec:
  schedule: {{ .Values.cronJob.cronJobSchedule | quote }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: {{ include "axetrading-cronjob.serviceAccountName" . }}
          containers:
            - name: {{ include "axetrading-cronjob.fullname" . }}-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              args : {{ .Values.cronJob.cronJobCommands }}
              volumeMounts:
               {{- if .Values.persistence.enabled }}
                - name: {{ include "axetrading-cronjob.fullname" . }}-data
                  mountPath: {{ .Values.persistence.mountPath }}
               {{- end }}
               {{- if .Values.secretsStore.enabled }}
                - name: {{ include "axetrading-cronjob.fullname" . }}-secrets-store
                  mountPath: /mnt/secrets/
                  readOnly: true
               {{- end }}
          restartPolicy: Never
          volumes:
          {{- if .Values.persistence.enabled }}
          - name: {{ include "axetrading-cronjob.fullname" . }}-data
            persistentVolumeClaim:
              claimName: {{ include "axetrading-cronjob.fullname" . }}-pvc
          {{- end }}
          {{- if .Values.secretsStore.enabled }}
          - name: {{ include "axetrading-cronjob.fullname" . }}-secrets-store
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: {{ include "axetrading-cronjob.fullname" . }}-secrets
          {{- end }}
