{{- if and .Values.cronJob.create }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "axetrading-api.fullname" . }}
  labels:
    {{- include "axetrading-api.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronJob.cronJobSchedule }}
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ include "axetrading-api.fullname" . }}-cronjob
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              args : {{ .Values.cronJob.cronJobCommands }}
              volumeMounts:
               {{- if .Values.persistence.enabled }}
                - name: {{ include "axetrading-api.fullname" . }}-data
                  mountPath: {{ .Values.persistence.mountPath }}
               {{- end }}
               {{- if .Values.secretsStore.enabled }}
                - name: {{ include "axetrading-api.fullname" . }}-secrets-store
                  mountPath: /mnt/secrets/
                  readOnly: true
               {{- end }}
          restartPolicy: Never
          serviceAccountName: {{ include "axetrading-api.serviceAccountName" . }}-cron
          volumes:
          {{- if .Values.persistence.enabled }}
          - name: {{ include "axetrading-api.fullname" . }}-data
            persistentVolumeClaim:
              claimName: {{ include "axetrading-api.fullname" . }}-pvc
          {{- end }}
          {{- if .Values.secretsStore.enabled }}
          - name: {{ include "axetrading-api.fullname" . }}-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ include "axetrading-api.fullname" . }}-secrets
          {{- end }}
{{- end }}