apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "axetrading-cronjob.fullname" . }}
  labels:
  {{- include "axetrading-cronjob.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - read
  - list
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
  - list
  - watch
  - patch
  - update
  

